# Generated by Django 5.0.7 on 2024-08-10 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStatsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_num', models.IntegerField(unique=True)),
                ('nickname', models.CharField(max_length=100)),
                ('season_id', models.IntegerField()),
                ('matching_mode', models.IntegerField(choices=[(2, 'Normal'), (3, 'Ranked')])),
                ('matching_team_mode', models.IntegerField(choices=[(1, 'Solo'), (2, 'Duo'), (3, 'Squad')])),
                ('mmr', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('rank_percent', models.FloatField()),
                ('rank_size', models.IntegerField()),
                ('total_games', models.IntegerField()),
                ('total_wins', models.IntegerField()),
                ('total_team_kills', models.IntegerField()),
                ('total_deaths', models.IntegerField()),
                ('escape_count', models.IntegerField()),
                ('average_rank', models.FloatField()),
                ('average_kills', models.FloatField()),
                ('average_assistants', models.FloatField()),
                ('average_hunts', models.FloatField()),
                ('top1', models.FloatField()),
                ('top2', models.FloatField()),
                ('top3', models.FloatField()),
                ('top5', models.FloatField()),
                ('top7', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CharacterStatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_id', models.IntegerField()),
                ('average_rank', models.FloatField()),
                ('character_code', models.IntegerField()),
                ('max_killings', models.IntegerField()),
                ('top3', models.IntegerField()),
                ('top3_rate', models.FloatField()),
                ('total_games', models.IntegerField()),
                ('usages', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('player_stats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_stats', to='nadia.playerstatsmodel')),
            ],
        ),
    ]
