# Generated by Django 5.0.7 on 2024-09-11 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('user_num', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MMRHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_mmr', models.FloatField()),
                ('high_mmr', models.FloatField()),
                ('low_mmr', models.FloatField()),
                ('close_mmr', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nadia.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_id', models.IntegerField()),
                ('matching_mode', models.IntegerField()),
                ('matching_team_mode', models.IntegerField()),
                ('mmr', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('rank_size', models.IntegerField()),
                ('rank_percent', models.FloatField()),
                ('total_games', models.IntegerField()),
                ('total_wins', models.IntegerField()),
                ('average_rank', models.FloatField()),
                ('total_team_kills', models.IntegerField()),
                ('average_kills', models.FloatField()),
                ('average_assistants', models.FloatField()),
                ('average_damage', models.FloatField()),
                ('average_hunts', models.FloatField()),
                ('top1', models.FloatField()),
                ('top2', models.FloatField()),
                ('top3', models.FloatField()),
                ('top5', models.FloatField()),
                ('top7', models.FloatField()),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nadia.player')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_code', models.IntegerField()),
                ('most_used_skin_code', models.IntegerField()),
                ('most_weapon', models.IntegerField()),
                ('most_tactical_skill_group', models.IntegerField()),
                ('most_trait_first_core', models.IntegerField()),
                ('most_trait_first_sub', models.JSONField()),
                ('most_trait_second_sub', models.JSONField()),
                ('total_games', models.IntegerField()),
                ('average_team_kills', models.FloatField()),
                ('average_kills', models.FloatField()),
                ('average_assistants', models.FloatField()),
                ('average_damage', models.FloatField()),
                ('average_rank', models.FloatField()),
                ('top1', models.FloatField()),
                ('top2', models.FloatField()),
                ('top3', models.FloatField()),
                ('earned_rp', models.IntegerField()),
                ('player_stats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nadia.playerstats')),
            ],
        ),
        migrations.AddIndex(
            model_name='playerstats',
            index=models.Index(fields=['player', 'season_id'], name='nadia_playe_player__11a7bd_idx'),
        ),
        migrations.AddIndex(
            model_name='playerstats',
            index=models.Index(fields=['player', 'season_id', 'matching_mode', 'matching_team_mode'], name='nadia_playe_player__960997_idx'),
        ),
    ]
