# Generated by Django 5.0.7 on 2024-08-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nadia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstatsmodel',
            name='user_num',
            field=models.IntegerField(),
        ),
    ]
