# Generated by Django 5.0.7 on 2024-09-09 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nadia', '0003_player_mmrhistory_playerstats_characterstats_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='id',
        ),
        migrations.AlterField(
            model_name='player',
            name='user_num',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
