services:
  nginx:
    image:
      nginx:latest
    ports:
      - "80:80"
    volumes:
      - .:/code
      - ./nginx.conf:/etc/nginx/nginx.conf
#      - ./nginx/nginx:/etc/nginx.conf.d
    depends_on:
      - django
  django:
    build: .
#    dockerfile: Dockerfile
    container_name: django_gunicorn
#    command: ["gunicorn", "--bind", "0.0.0.0:8000", "AglaiaLabBE.wsgi:application"]
    command: gunicorn AglaiaLabBE.wsgi:application --bind 0.0.0.0:8000
#    ports:
#      - "8000:8000"
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=AglaiaLabBE.settings.local
    volumes:
      - .:/code
    expose:
      - "8000"
