# Generated by Django 5.0.7 on 2024-09-11 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thomas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='battlerecord',
            old_name='team_kills',
            new_name='team_kill',
        ),
    ]
