# Generated by Django 5.0.7 on 2024-09-11 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thomas', '0002_rename_team_kills_battlerecord_team_kill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinfo',
            name='mmr_avg',
            field=models.IntegerField(null=True),
        ),
    ]
