# Generated by Django 5.0.7 on 2024-09-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thomas', '0002_alter_battlerecord_place_of_death_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinfo',
            name='mmrAfter',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='mmrBefore',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='mmrGain',
            field=models.IntegerField(null=True),
        ),
    ]
