# Generated by Django 5.0.7 on 2024-09-11 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thomas', '0003_alter_gameinfo_mmr_avg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battlerecord',
            name='game',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='battlerecord', to='thomas.gameinfo'),
        ),
        migrations.AlterField(
            model_name='equipmentandtraits',
            name='game',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_and_traits', to='thomas.gameinfo'),
        ),
    ]
