# Generated by Django 5.0.7 on 2024-09-09 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thomas', '0003_gameinfo_mmrafter_gameinfo_mmrbefore_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameinfo',
            old_name='mmrAfter',
            new_name='mmr_after',
        ),
        migrations.RenameField(
            model_name='gameinfo',
            old_name='mmrBefore',
            new_name='mmr_before',
        ),
        migrations.RenameField(
            model_name='gameinfo',
            old_name='mmrGain',
            new_name='mmr_gain',
        ),
    ]
