# Generated by Django 5.0.7 on 2024-09-11 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thomas', '0004_alter_battlerecord_game_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battlerecord',
            name='game',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='battle_record', to='thomas.gameinfo'),
        ),
    ]
